# Generated by Django 3.2.5 on 2023-09-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='image',
        ),
        migrations.AlterField(
            model_name='timecodes',
            name='end',
            field=models.PositiveIntegerField(verbose_name='Конец в секундах'),
        ),
        migrations.AlterField(
            model_name='timecodes',
            name='start',
            field=models.PositiveIntegerField(verbose_name='Начало в секундах'),
        ),
    ]
